"""
Phase 3.4 -- Stage 2 (Reasoning Fine-Tune) Training

Multi-GPU training with 4x H100s. Native bfloat16, no bitsandbytes.
Initializes from Stage 1 checkpoint and fine-tunes on reasoning Q&A data
generated by GPT-4o-mini.

DDP is used for parameter broadcasting at init, but gradient sync is
handled manually (all-reduce on trainable grads only) via no_sync() to
prevent NCCL deadlocks when individual ranks hit NaN/OOM.

Key differences from Stage 1:
  - Loads Stage 1 projector + LoRA weights before training
  - Dataset: JSONL with sequence_tensors (multi-chunk) + qa_pairs
  - Each record can produce multiple training examples (one per Q&A pair)
  - Lower learning rates (half of Stage 1) to preserve Stage 1 knowledge
  - Multi-chunk vision: concatenate features from all chunks, project each,
    then concatenate projected tokens

Architecture unchanged:
  Code image -> SigLIP features [1024, 1152]
             -> ConvRoPEProjector [256, 2048]
             -> splice into token embeddings at placeholder positions
             -> DeepSeek-Coder-V2-Lite-Instruct (bfloat16 + LoRA)
             -> cross-entropy loss on answer tokens only
"""

import os
os.environ["PYTHONNOUSERSITE"] = "1"

import argparse
import json
import math
import torch
import torch.nn as nn
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, Dataset, random_split
from torch.utils.data.distributed import DistributedSampler
from pathlib import Path
from typing import Optional, List, Dict
from transformers import AutoModelForCausalLM, AutoTokenizer, get_cosine_schedule_with_warmup
from peft import LoraConfig, get_peft_model, PeftModel
from tqdm import tqdm
import traceback

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MAX_TEXT_TOKENS = 768
N_VISUAL_TOKENS = 256        # per chunk (output of ConvRoPEProjector)
GRAD_ACCUM_STEPS = 2         # 4 per GPU * 4 GPUs * 2 accum = effective 32
LR_PROJECTOR = 5e-6          # half of Stage 1 (was 1e-5)
LR_LORA = 2e-6               # half of Stage 1 (was 5e-6)
BATCH_SIZE = 4                # per GPU
VAL_SPLIT = 0.05
SEED = 42
LORA_R = 32
LORA_ALPHA = 64
LORA_DROPOUT = 0.05
WARMUP_RATIO = 0.03
EPOCHS = 3
MAX_CHUNKS = 5               # max number of vision chunks per sample (safety cap)


# ---------------------------------------------------------------------------
# ConvRoPEProjector  (copied from Stage 1 -- must be identical for weight loading)
# ---------------------------------------------------------------------------
def _sinusoidal_freqs(seq_len: int, half_dim: int, device: torch.device):
    """Return (cos, sin) tables each [seq_len, half_dim]."""
    i      = torch.arange(half_dim, device=device, dtype=torch.float32)
    theta  = 1.0 / (10000.0 ** (i / half_dim))
    pos    = torch.arange(seq_len, device=device, dtype=torch.float32)
    angles = torch.outer(pos, theta)
    return angles.cos(), angles.sin()


def _rope_rotate(x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor) -> torch.Tensor:
    """Apply RoPE rotation. x: [..., seq_len, 2*half_dim]."""
    half = x.shape[-1] // 2
    x1, x2 = x[..., :half], x[..., half:]
    return torch.cat([x1 * cos - x2 * sin, x1 * sin + x2 * cos], dim=-1)


def apply_2d_rope_16x16(x: torch.Tensor) -> torch.Tensor:
    """Apply 2D RoPE on post-convolution 16x16 grid (256 tokens)."""
    B, T, D = x.shape
    assert T == 256 and D == 1152, f"Expected [B,256,1152], got {x.shape}"
    half_D   = D // 2
    half_dim = half_D // 2
    device   = x.device
    rows = torch.arange(256, device=device) // 16
    cols = torch.arange(256, device=device) % 16
    cos_table, sin_table = _sinusoidal_freqs(16, half_dim, device)
    cos_table = cos_table.to(x.dtype)
    sin_table = sin_table.to(x.dtype)
    cos_row = cos_table[rows]
    sin_row = sin_table[rows]
    cos_col = cos_table[cols]
    sin_col = sin_table[cols]
    x_row = x[:, :, :half_D]
    x_col = x[:, :, half_D:]
    x_row_rot = _rope_rotate(x_row, cos_row, sin_row)
    x_col_rot = _rope_rotate(x_col, cos_col, sin_col)
    return torch.cat([x_row_rot, x_col_rot], dim=-1)


class ConvRoPEProjector(nn.Module):
    """Compresses [B, 1024, 1152] raw SigLIP tokens to [B, 256, 2048]."""
    def __init__(self, feat_dim: int = 1152, proj_dim: int = 2048) -> None:
        super().__init__()
        self.feat_dim = feat_dim
        self.grid_in  = 32
        self.grid_out = 16
        self.conv = nn.Conv2d(feat_dim, feat_dim, kernel_size=2, stride=2)
        self.mlp = nn.Sequential(
            nn.Linear(feat_dim, proj_dim),
            nn.GELU(),
            nn.Linear(proj_dim, proj_dim),
        )
        self._init_weights()

    def _init_weights(self) -> None:
        nn.init.kaiming_normal_(self.conv.weight, mode="fan_out", nonlinearity="relu")
        nn.init.zeros_(self.conv.bias)
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, N, C = x.shape
        assert N == self.grid_in ** 2 and C == self.feat_dim
        x = x.to(self.conv.weight.dtype)
        x = x.reshape(B, self.grid_in, self.grid_in, C).permute(0, 3, 1, 2)
        x = self.conv(x)
        x = x.flatten(2).transpose(1, 2)
        x = apply_2d_rope_16x16(x)
        x = self.mlp(x)
        return x


# ---------------------------------------------------------------------------
# CoderVLModel (multi-chunk aware)
# ---------------------------------------------------------------------------
class CoderVLModel(nn.Module):
    """Wraps ConvRoPEProjector + LoRA-adapted DeepSeek LLM for DDP training.

    For Stage 2, vision input is [B, n_chunks * 1024, 1152] -- we project each
    chunk of 1024 tokens separately through the projector, then concatenate the
    resulting [B, n_chunks * 256, 2048] visual embeddings.
    """
    def __init__(self, projector: ConvRoPEProjector, llm: nn.Module) -> None:
        super().__init__()
        self.projector = projector
        self.llm = llm

    def forward(self, vision, input_ids, attention_mask, labels, n_visual_tokens: int):
        """
        Args:
            vision: [B, n_chunks * 1024, 1152] raw SigLIP features
            input_ids: [B, S] token ids (placeholders at start for visual tokens)
            attention_mask: [B, S]
            labels: [B, S] with -100 for non-target positions
            n_visual_tokens: total visual tokens per sample in this batch
                             (= n_chunks * N_VISUAL_TOKENS)
        """
        B, S = input_ids.shape
        total_sig_tokens = vision.shape[1]
        n_chunks = total_sig_tokens // 1024

        # Project each chunk separately (projector expects [B, 1024, 1152])
        projected_chunks = []
        for i in range(n_chunks):
            chunk = vision[:, i * 1024 : (i + 1) * 1024, :]
            projected_chunks.append(self.projector(chunk))

        # Concatenate: [B, n_chunks * 256, 2048]
        visual_embeds = torch.cat(projected_chunks, dim=1)

        # Get text embeddings (no grad through embedding layer)
        with torch.no_grad():
            text_embeds = self.llm.get_input_embeddings()(input_ids)
        text_embeds = text_embeds.clone()

        # Splice visual embeddings into placeholder positions
        visual_embeds = visual_embeds.to(dtype=text_embeds.dtype)
        text_embeds[:, :n_visual_tokens, :] = visual_embeds

        position_ids = torch.arange(S, device=input_ids.device).unsqueeze(0).expand(B, -1)
        outputs = self.llm(
            inputs_embeds=text_embeds,
            attention_mask=attention_mask,
            position_ids=position_ids,
            labels=labels,
            use_cache=False,
            return_dict=True,
        )
        return outputs.loss


# ---------------------------------------------------------------------------
# ReasoningDataset
# ---------------------------------------------------------------------------
class ReasoningDataset(Dataset):
    """Loads reasoning Q&A data from a JSONL file.

    Each JSONL record has:
      - sequence_tensors: list of paths to precomputed SigLIP [1024, 1152] .pt files
      - qa_pairs: list of {question, answer} dicts

    One record produces len(qa_pairs) training examples. We flatten all
    (record, qa_pair_index) tuples at init time for efficient indexing.
    """

    def __init__(
        self,
        jsonl_path: str,
        tokenizer,
        repo_root: str,
        max_text_tokens: int = MAX_TEXT_TOKENS,
        max_chunks: int = MAX_CHUNKS,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_text_tokens = max_text_tokens
        self.max_chunks = max_chunks
        self.repo_root = Path(repo_root)

        # Load JSONL and flatten to (record, qa_index) pairs
        self.records: List[Dict] = []
        self.flat_samples: List[tuple] = []  # (record_idx, qa_idx)

        jsonl_path = Path(jsonl_path)
        if not jsonl_path.exists():
            raise FileNotFoundError(f"Reasoning dataset not found: {jsonl_path}")

        with open(jsonl_path, "r", encoding="utf-8") as f:
            for line_num, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError as e:
                    print(f"[ReasoningDataset] Skipping malformed line {line_num}: {e}")
                    continue

                # Validate required fields
                if "sequence_tensors" not in record or "qa_pairs" not in record:
                    print(f"[ReasoningDataset] Skipping line {line_num}: missing fields")
                    continue
                if not record["qa_pairs"]:
                    continue

                # Cap chunks
                tensors = record["sequence_tensors"][:self.max_chunks]
                record["sequence_tensors"] = tensors

                rec_idx = len(self.records)
                self.records.append(record)

                for qa_idx in range(len(record["qa_pairs"])):
                    self.flat_samples.append((rec_idx, qa_idx))

        print(f"[ReasoningDataset] Loaded {len(self.records)} records, "
              f"{len(self.flat_samples)} Q&A samples from {jsonl_path}")

    def __len__(self) -> int:
        return len(self.flat_samples)

    def __getitem__(self, idx: int) -> Optional[dict]:
        rec_idx, qa_idx = self.flat_samples[idx]
        record = self.records[rec_idx]

        try:
            # Load and concatenate vision tensors
            tensor_paths = record["sequence_tensors"]
            n_chunks = len(tensor_paths)

            vision_chunks = []
            for tp in tensor_paths:
                full_path = self.repo_root / tp
                if not full_path.exists():
                    print(f"[ReasoningDataset] Missing tensor: {full_path}")
                    return None
                chunk = torch.load(str(full_path), map_location="cpu", weights_only=True)
                # Cast to float32 for safety (will be cast to bfloat16 later)
                chunk = chunk.float()
                if chunk.shape != (1024, 1152):
                    print(f"[ReasoningDataset] Bad shape {chunk.shape} in {full_path}")
                    return None
                vision_chunks.append(chunk)

            # Concatenate: [n_chunks * 1024, 1152]
            vision = torch.cat(vision_chunks, dim=0)

            # Get Q&A
            qa = record["qa_pairs"][qa_idx]
            question = qa["question"]
            answer = qa["answer"]

            # Tokenize
            pad_id = self.tokenizer.pad_token_id
            eos_id = self.tokenizer.eos_token_id

            n_visual_tokens = n_chunks * N_VISUAL_TOKENS

            # Format: [visual_placeholders] \nQuestion: {question}\nAnswer: {answer}<eos>
            prompt_text = f"\nQuestion: {question}\nAnswer: "
            prompt_ids = self.tokenizer.encode(prompt_text, add_special_tokens=False)

            answer_ids = self.tokenizer.encode(answer, add_special_tokens=False)

            # Truncate answer if needed (leave room for prompt + eos)
            max_answer_len = self.max_text_tokens - len(prompt_ids) - 1  # -1 for eos
            if max_answer_len <= 0:
                # Prompt alone exceeds budget -- truncate prompt
                prompt_ids = prompt_ids[:self.max_text_tokens // 2]
                max_answer_len = self.max_text_tokens - len(prompt_ids) - 1

            if len(answer_ids) > max_answer_len:
                answer_ids = answer_ids[:max_answer_len]

            placeholder = [pad_id] * n_visual_tokens
            input_ids = placeholder + prompt_ids + answer_ids + [eos_id]

            # Labels: only supervise on the answer tokens + eos
            labels = (
                [-100] * n_visual_tokens
                + [-100] * len(prompt_ids)
                + answer_ids
                + [eos_id]
            )

            assert len(input_ids) == len(labels), \
                f"Length mismatch: input_ids={len(input_ids)}, labels={len(labels)}"

            return {
                "vision": vision,
                "input_ids": torch.tensor(input_ids, dtype=torch.long),
                "labels": torch.tensor(labels, dtype=torch.long),
                "n_chunks": n_chunks,
            }

        except Exception as e:
            print(f"[ReasoningDataset] Error loading record {rec_idx}, qa {qa_idx}: {e}")
            traceback.print_exc()
            return None


# ---------------------------------------------------------------------------
# collate_fn
# ---------------------------------------------------------------------------
def collate_fn(batch: list) -> Optional[dict]:
    """Collate with None filtering, right-padding, and multi-chunk vision padding.

    All samples in a batch must have the same number of vision chunks (we pad
    to the max n_chunks in the batch by repeating the last chunk's features).
    """
    batch = [b for b in batch if b is not None]
    if not batch:
        return None

    pad_id = collate_fn.pad_token_id

    # Find max chunks and max text length in this batch
    max_chunks = max(b["n_chunks"] for b in batch)
    max_visual_tokens = max_chunks * N_VISUAL_TOKENS
    max_text_len = max(b["input_ids"].size(0) for b in batch)

    # We need to re-pad input_ids and labels so visual placeholder region
    # matches max_visual_tokens for all samples
    vision_list = []
    input_ids_list = []
    labels_list = []
    attention_mask_list = []

    for b in batch:
        n_chunks = b["n_chunks"]
        n_visual = n_chunks * N_VISUAL_TOKENS
        extra_visual = max_visual_tokens - n_visual

        # Pad vision to max_chunks * 1024 tokens
        vis = b["vision"]  # [n_chunks * 1024, 1152]
        if n_chunks < max_chunks:
            # Pad with zeros (projector output for zero input will be near-zero)
            pad_vis = torch.zeros(
                (max_chunks - n_chunks) * 1024, 1152, dtype=vis.dtype
            )
            vis = torch.cat([vis, pad_vis], dim=0)
        vision_list.append(vis)

        # Original ids without visual placeholders
        orig_ids = b["input_ids"]
        orig_labels = b["labels"]
        text_ids = orig_ids[n_visual:]
        text_labels = orig_labels[n_visual:]

        # New placeholder + text
        new_placeholder_ids = torch.full((max_visual_tokens,), pad_id, dtype=torch.long)
        new_placeholder_labels = torch.full((max_visual_tokens,), -100, dtype=torch.long)

        new_ids = torch.cat([new_placeholder_ids, text_ids])
        new_labels = torch.cat([new_placeholder_labels, text_labels])

        # Right-pad text to match max total length
        total_len = max_visual_tokens + (max_text_len - n_visual)
        current_len = new_ids.size(0)
        pad_len = total_len - current_len

        if pad_len > 0:
            new_ids = torch.cat([new_ids, torch.full((pad_len,), pad_id, dtype=torch.long)])
            new_labels = torch.cat([new_labels, torch.full((pad_len,), -100, dtype=torch.long)])
        elif pad_len < 0:
            # Truncate (shouldn't happen, but safety)
            new_ids = new_ids[:total_len]
            new_labels = new_labels[:total_len]

        mask_len = max_visual_tokens + text_ids.size(0)
        total_final = new_ids.size(0)
        mask = torch.zeros(total_final, dtype=torch.long)
        mask[:mask_len] = 1

        input_ids_list.append(new_ids)
        labels_list.append(new_labels)
        attention_mask_list.append(mask)

    return {
        "vision": torch.stack(vision_list),
        "input_ids": torch.stack(input_ids_list),
        "attention_mask": torch.stack(attention_mask_list),
        "labels": torch.stack(labels_list),
        "n_visual_tokens": max_visual_tokens,
    }

collate_fn.pad_token_id = 0


# ---------------------------------------------------------------------------
# DDP helpers
# ---------------------------------------------------------------------------
def setup_ddp():
    """Initialize distributed process group and set local device."""
    dist.init_process_group(backend="nccl")
    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    return local_rank


def cleanup_ddp():
    """Destroy the distributed process group."""
    dist.destroy_process_group()


def is_main_process():
    """True only on rank 0."""
    return int(os.environ.get("RANK", 0)) == 0


# ---------------------------------------------------------------------------
# Model loading with Stage 1 checkpoint
# ---------------------------------------------------------------------------
def load_model(model_path: str, stage1_ckpt_dir: str, device: torch.device):
    """Load tokenizer, bfloat16 LLM with LoRA, ConvRoPEProjector,
    then restore Stage 1 weights (projector + LoRA adapter)."""

    if is_main_process():
        print(f"[load_model] Loading tokenizer from {model_path}")
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    if is_main_process():
        print(f"[load_model] Loading LLM in bfloat16 from {model_path}")
    llm = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map={"": device},
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
    )

    # ---- Load Stage 1 LoRA adapter ----
    stage1_dir = Path(stage1_ckpt_dir)
    lora_adapter_dir = stage1_dir / "lora_adapter"

    if lora_adapter_dir.exists():
        if is_main_process():
            print(f"[load_model] Loading Stage 1 LoRA adapter from {lora_adapter_dir}")
        llm = PeftModel.from_pretrained(
            llm,
            str(lora_adapter_dir),
            is_trainable=True,
        )
        if is_main_process():
            print("[load_model] Stage 1 LoRA adapter loaded successfully")
    else:
        if is_main_process():
            print(f"[load_model] WARNING: No Stage 1 LoRA adapter at {lora_adapter_dir}")
            print("[load_model] Applying fresh LoRA config (Stage 1 LoRA weights missing!)")
        lora_config = LoraConfig(
            r=LORA_R,
            lora_alpha=LORA_ALPHA,
            lora_dropout=LORA_DROPOUT,
            target_modules=[
                "q_proj", "kv_a_proj_with_mqa", "kv_b_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
            bias="none",
            task_type="CAUSAL_LM",
        )
        llm = get_peft_model(llm, lora_config)

    if is_main_process():
        llm.print_trainable_parameters()

    # ---- Projector ----
    projector = ConvRoPEProjector(feat_dim=1152, proj_dim=2048)

    projector_ckpt_path = stage1_dir / "projector.pth"
    if projector_ckpt_path.exists():
        if is_main_process():
            print(f"[load_model] Loading Stage 1 projector from {projector_ckpt_path}")
        ckpt = torch.load(str(projector_ckpt_path), map_location="cpu", weights_only=True)
        if "projector_state_dict" in ckpt:
            projector.load_state_dict(ckpt["projector_state_dict"])
        else:
            projector.load_state_dict(ckpt)
        if is_main_process():
            print("[load_model] Projector weights loaded successfully")
    else:
        if is_main_process():
            print(f"[load_model] WARNING: No projector checkpoint at {projector_ckpt_path}")
            print("[load_model] Using random init (Stage 1 projector weights missing!)")

    projector.to(device=device, dtype=torch.bfloat16)

    model = CoderVLModel(projector, llm)

    # Print param counts
    if is_main_process():
        proj_trainable = sum(p.numel() for p in model.projector.parameters() if p.requires_grad)
        lora_trainable = sum(p.numel() for p in model.llm.parameters() if p.requires_grad)
        frozen = sum(p.numel() for p in model.llm.parameters() if not p.requires_grad)
        print(f"[load_model] Projector trainable params: {proj_trainable:,}")
        print(f"[load_model] LoRA trainable params:      {lora_trainable:,}")
        print(f"[load_model] Frozen LLM params:          {frozen:,}")

    return model, tokenizer


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
def validate(model: nn.Module, val_loader: DataLoader, device: torch.device) -> float:
    """Run validation on all ranks (NCCL timeout safety), return average loss."""
    model.eval()
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch in val_loader:
            if batch is None:
                continue
            vision = batch["vision"].to(device)
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            n_visual_tokens = batch["n_visual_tokens"]

            try:
                with torch.cuda.amp.autocast(dtype=torch.bfloat16):
                    loss = model(vision, input_ids, attention_mask, labels, n_visual_tokens)
                if not torch.isfinite(loss):
                    continue
                total_loss += loss.item()
                n_batches += 1
            except RuntimeError as e:
                if "out of memory" in str(e):
                    torch.cuda.empty_cache()
                    continue
                raise

    model.train()
    return total_loss / n_batches if n_batches > 0 else float("inf")


# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------
def save_checkpoint(model: CoderVLModel, save_dir: Path, tag: str) -> None:
    """Save projector weights and LoRA adapter. Only call on rank 0."""
    ckpt_dir = save_dir / f"epoch_{tag}"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    torch.save(
        {"projector_state_dict": model.projector.state_dict()},
        str(ckpt_dir / "projector.pth"),
    )
    model.llm.save_pretrained(str(ckpt_dir / "lora_adapter"))
    print(f"[save_checkpoint] Saved checkpoint to {ckpt_dir}")


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------
def train(model, tokenizer, jsonl_path, repo_root, save_dir, epochs, batch_size, local_rank):
    """Main DDP training loop with cosine LR schedule, validation, and checkpointing."""
    device = torch.device(f"cuda:{local_rank}")
    save_dir = Path(save_dir)
    if is_main_process():
        save_dir.mkdir(parents=True, exist_ok=True)

    # Dataset and split
    full_dataset = ReasoningDataset(jsonl_path, tokenizer, repo_root)
    val_size = max(1, int(len(full_dataset) * VAL_SPLIT))
    train_size = len(full_dataset) - val_size
    train_dataset, val_dataset = random_split(
        full_dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(SEED),
    )
    if is_main_process():
        print(f"[train] Train: {train_size}, Val: {val_size}")
        print(f"[train] (from {len(full_dataset.records)} JSONL records, "
              f"{len(full_dataset)} total Q&A samples)")

    collate_fn.pad_token_id = tokenizer.pad_token_id

    # DistributedSamplers
    train_sampler = DistributedSampler(train_dataset, shuffle=True, seed=SEED)
    val_sampler = DistributedSampler(val_dataset, shuffle=False)

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, sampler=train_sampler,
        num_workers=4, pin_memory=True, collate_fn=collate_fn,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=batch_size, sampler=val_sampler,
        num_workers=2, pin_memory=True, collate_fn=collate_fn,
    )

    # Wrap in DDP — broadcast_buffers=False prevents allreduce on non-trainable
    # buffers. We use no_sync() everywhere and manually all-reduce trainable grads,
    # so DDP only handles parameter broadcasting at init.
    ddp_model = DDP(model, device_ids=[local_rank], find_unused_parameters=False, broadcast_buffers=False)

    # Optimizer -- two param groups (use unwrapped model)
    optimizer = torch.optim.AdamW([
        {"params": model.projector.parameters(), "lr": LR_PROJECTOR},
        {"params": [p for p in model.llm.parameters() if p.requires_grad], "lr": LR_LORA},
    ])

    # LR scheduler -- linear warmup + cosine decay
    # Account for grad accumulation in total steps calculation
    steps_per_epoch = math.ceil(len(train_loader) / GRAD_ACCUM_STEPS)
    total_steps = steps_per_epoch * epochs
    warmup_steps = int(total_steps * WARMUP_RATIO)
    scheduler = get_cosine_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    if is_main_process():
        print(f"[train] Total optimizer steps: {total_steps}, warmup: {warmup_steps}")
        print(f"[train] Grad accum steps: {GRAD_ACCUM_STEPS}")
        print(f"[train] Effective batch size: {batch_size} * {dist.get_world_size()} * "
              f"{GRAD_ACCUM_STEPS} = {batch_size * dist.get_world_size() * GRAD_ACCUM_STEPS}")
        print(f"[train] LR projector: {LR_PROJECTOR}, LR LoRA: {LR_LORA}")

    best_val_loss = float("inf")
    skipped_batches = 0

    # Collect trainable params once (for gradient sync + clipping)
    all_params = (
        list(model.projector.parameters())
        + [p for p in model.llm.parameters() if p.requires_grad]
    )

    world_size = dist.get_world_size()

    def sync_gradients():
        """All-reduce trainable gradients across ranks, average by world_size.
        Initializes missing grads to zero so ALL ranks participate in every
        all_reduce call, preventing NCCL deadlocks when some ranks skip backward."""
        for p in all_params:
            if p.grad is None:
                p.grad = torch.zeros_like(p.data)
            dist.all_reduce(p.grad, op=dist.ReduceOp.SUM)
            p.grad.div_(world_size)

    for epoch in range(epochs):
        train_sampler.set_epoch(epoch)
        ddp_model.train()

        epoch_loss = 0.0
        n_steps = 0
        accum_step = 0
        optimizer_steps = 0

        loader_iter = train_loader
        if is_main_process():
            loader_iter = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")

        optimizer.zero_grad()

        for batch_idx, batch in enumerate(loader_iter):
            got_loss = False

            with ddp_model.no_sync():
                if batch is not None:
                    vision = batch["vision"].to(device)
                    input_ids = batch["input_ids"].to(device)
                    attention_mask = batch["attention_mask"].to(device)
                    labels = batch["labels"].to(device)
                    n_visual_tokens = batch["n_visual_tokens"]

                    try:
                        with torch.cuda.amp.autocast(dtype=torch.bfloat16):
                            loss = ddp_model(vision, input_ids, attention_mask, labels, n_visual_tokens)
                        if not torch.isfinite(loss):
                            print(f"[train] NaN/Inf loss at batch {batch_idx}, skipping")
                            optimizer.zero_grad()
                            skipped_batches += 1
                        else:
                            scaled_loss = loss / GRAD_ACCUM_STEPS
                            scaled_loss.backward()
                            got_loss = True
                    except RuntimeError as e:
                        if "out of memory" in str(e):
                            print(f"[train] OOM on batch {batch_idx} (n_visual={n_visual_tokens}, "
                                  f"seq_len={input_ids.shape[1]}), skipping")
                            torch.cuda.empty_cache()
                            optimizer.zero_grad()
                            skipped_batches += 1
                        else:
                            raise
                else:
                    skipped_batches += 1

            accum_step += 1

            if accum_step % GRAD_ACCUM_STEPS == 0:
                sync_gradients()
                torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()
                optimizer_steps += 1

            if got_loss:
                epoch_loss += loss.item()
                n_steps += 1

                # Mid-epoch checkpoint every 500 optimizer steps
                if optimizer_steps > 0 and optimizer_steps % 500 == 0 and is_main_process():
                    save_checkpoint(model, save_dir, f"step_{optimizer_steps}")
                    save_checkpoint(model, save_dir, "latest")
                    print(f"[train] Mid-epoch checkpoint at optimizer step {optimizer_steps}")

            if got_loss and is_main_process() and hasattr(loader_iter, "set_postfix"):
                loader_iter.set_postfix(
                    loss=f"{loss.item():.4f}",
                    lr_proj=f"{scheduler.get_last_lr()[0]:.2e}",
                    lr_lora=f"{scheduler.get_last_lr()[1]:.2e}",
                )

        # Handle leftover accumulated gradients
        if accum_step % GRAD_ACCUM_STEPS != 0:
            sync_gradients()
            torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()

        avg_train_loss = epoch_loss / n_steps if n_steps > 0 else float("inf")
        if is_main_process():
            print(f"[train] Epoch {epoch+1}/{epochs} -- train_loss: {avg_train_loss:.4f}")
            if skipped_batches > 0:
                print(f"[train] Skipped {skipped_batches} batches total so far")

        # Validation (all ranks to avoid NCCL timeout)
        val_loss = validate(ddp_model, val_loader, device)
        if is_main_process():
            print(f"[train] Epoch {epoch+1}/{epochs} -- val_loss:   {val_loss:.4f}")

        # Checkpoint (rank 0 only)
        if is_main_process():
            save_checkpoint(model, save_dir, str(epoch + 1))
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                save_checkpoint(model, save_dir, "best")
                print(f"[train] New best val_loss: {best_val_loss:.4f}")

        # Barrier so all ranks wait for checkpointing to finish
        dist.barrier()

    if is_main_process():
        print(f"[train] Training complete. Best val_loss: {best_val_loss:.4f}")
        print(f"[train] Total skipped batches: {skipped_batches}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    local_rank = setup_ddp()
    device = torch.device(f"cuda:{local_rank}")

    torch.manual_seed(SEED)

    parser = argparse.ArgumentParser(description="Phase 3.4 -- Stage 2 Reasoning Fine-Tune")
    parser.add_argument("--jsonl-path", type=str,
                        default="MVV/Phase_3/Phase_3_4/reasoning_dataset.jsonl",
                        help="Path to reasoning Q&A JSONL dataset")
    parser.add_argument("--repo-root", type=str,
                        default="/home/ad.msoe.edu/gloriosog/CoderOCR/OCR-Coder",
                        help="Repo root for resolving relative tensor paths")
    parser.add_argument("--model-path", type=str, required=True,
                        help="Path to DeepSeek-Coder-V2-Lite-Instruct model")
    parser.add_argument("--stage1-ckpt-dir", type=str,
                        default="MVV/Phase_3/checkpoints/stage1_run/epoch_best",
                        help="Path to Stage 1 best checkpoint directory "
                             "(containing projector.pth and lora_adapter/)")
    parser.add_argument("--save-dir", type=str,
                        default="MVV/Phase_3/checkpoints/stage2_run",
                        help="Directory for saving Stage 2 checkpoints")
    parser.add_argument("--epochs", type=int, default=EPOCHS)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    args = parser.parse_args()

    if is_main_process():
        print(f"[main] Starting Stage 2 Reasoning Fine-Tune")
        print(f"[main] JSONL: {args.jsonl_path}")
        print(f"[main] Stage 1 checkpoint: {args.stage1_ckpt_dir}")
        print(f"[main] GPUs: {dist.get_world_size()}")

    model, tokenizer = load_model(args.model_path, args.stage1_ckpt_dir, device)
    train(
        model, tokenizer,
        args.jsonl_path, args.repo_root,
        args.save_dir, args.epochs, args.batch_size, local_rank,
    )

    cleanup_ddp()


if __name__ == "__main__":
    main()
